"""Create learning tables (courses, lessons, enrollments, lesson_progress)

Revision ID: a859556b301a
Revises: 49d0c4a0ccde
Create Date: 2025-12-15 06:30:16.053453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a859556b301a'
down_revision: Union[str, None] = '49d0c4a0ccde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='URL-friendly course identifier'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False, comment='Brief course summary'),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('instructor_name', sa.String(length=255), nullable=False, comment='Cached instructor name for performance'),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False, comment="Course category (e.g., 'Programming', 'Design', 'Business')"),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True, comment='Array of searchable tags'),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('trailer_url', sa.String(length=500), nullable=True, comment='Course preview/trailer video URL'),
    sa.Column('total_lessons', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False, comment='Estimated time to complete in minutes'),
    sa.Column('prerequisites', postgresql.ARRAY(sa.UUID()), nullable=True, comment='Array of prerequisite course IDs'),
    sa.Column('required_skills', postgresql.ARRAY(sa.String()), nullable=True, comment='Skills required before taking this course'),
    sa.Column('learning_outcomes', postgresql.ARRAY(sa.String()), nullable=True, comment='What students will learn'),
    sa.Column('skills_gained', postgresql.ARRAY(sa.String()), nullable=True, comment='Skills acquired after completion'),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True, comment='Course price (if not free)'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_ai_recommended', sa.Boolean(), nullable=False, comment='True if AI recommends this course'),
    sa.Column('ai_match_score', sa.Float(), nullable=True, comment='AI match score for user (0-100)'),
    sa.Column('enrollment_count', sa.Integer(), nullable=False),
    sa.Column('completion_count', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('has_certificate', sa.Boolean(), nullable=False, comment='Whether course awards a certificate'),
    sa.Column('certificate_template', sa.String(length=100), nullable=True, comment='Certificate template name'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional course metadata'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='When course was published'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_category'), 'courses', ['category'], unique=False)
    op.create_index(op.f('ix_courses_created_at'), 'courses', ['created_at'], unique=False)
    op.create_index(op.f('ix_courses_difficulty'), 'courses', ['difficulty'], unique=False)
    op.create_index('ix_courses_difficulty_category', 'courses', ['difficulty', 'category'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_instructor_id'), 'courses', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_index(op.f('ix_courses_status'), 'courses', ['status'], unique=False)
    op.create_index('ix_courses_status_created', 'courses', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lesson_type', sa.String(length=20), nullable=False),
    sa.Column('content_url', sa.String(length=500), nullable=True, comment='Video URL, document URL, etc.'),
    sa.Column('content_text', sa.Text(), nullable=True, comment='Text content for text-based lessons'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False, comment='Estimated lesson duration'),
    sa.Column('order', sa.Integer(), nullable=False, comment='Lesson order within the course'),
    sa.Column('is_preview', sa.Boolean(), nullable=False, comment='True if lesson is available as preview'),
    sa.Column('quiz_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of quiz question objects (for quiz lessons)'),
    sa.Column('passing_score', sa.Integer(), nullable=True, comment='Minimum score to pass (for quiz lessons)'),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Downloadable resources, links, etc.'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional lesson metadata'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_index('ix_lessons_course_order', 'lessons', ['course_id', 'order'], unique=False)
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_index(op.f('ix_lessons_lesson_type'), 'lessons', ['lesson_type'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False, comment='Overall course completion percentage (0-100)'),
    sa.Column('lessons_completed', sa.Integer(), nullable=False),
    sa.Column('current_lesson_id', sa.UUID(), nullable=True, comment='Last lesson user was on'),
    sa.Column('total_time_spent_minutes', sa.Integer(), nullable=False, comment='Total time spent on course'),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True, comment='Final course score (if applicable)'),
    sa.Column('certificate_issued', sa.Boolean(), nullable=False),
    sa.Column('certificate_id', sa.String(length=100), nullable=True, comment='Unique certificate identifier'),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional enrollment metadata'),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True, comment='When user last accessed the course'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_id')
    )
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_enrolled_at'), 'enrollments', ['enrolled_at'], unique=False)
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    op.create_index('ix_enrollments_status_enrolled', 'enrollments', ['status', 'enrolled_at'], unique=False)
    op.create_index('ix_enrollments_user_course', 'enrollments', ['user_id', 'course_id'], unique=True)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False, comment='Lesson completion percentage (0-100)'),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('quiz_score', sa.Float(), nullable=True, comment='Score on quiz (if applicable)'),
    sa.Column('quiz_attempts', sa.Integer(), nullable=False),
    sa.Column('quiz_passed', sa.Boolean(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True, comment="User's notes for this lesson"),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_progress_enrollment_id'), 'lesson_progress', ['enrollment_id'], unique=False)
    op.create_index('ix_lesson_progress_enrollment_lesson', 'lesson_progress', ['enrollment_id', 'lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_id'), 'lesson_progress', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    op.create_index('ix_lesson_progress_user_lesson', 'lesson_progress', ['user_id', 'lesson_id'], unique=True)
    op.drop_index('ix_conversations_last_message_at_desc', table_name='conversations')
    op.create_index('ix_conversations_last_message_at_desc', 'conversations', ['last_message_at'], unique=False, postgresql_using='btree', postgresql_ops={'last_message_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_last_message_at_desc', table_name='conversations', postgresql_using='btree', postgresql_ops={'last_message_at': 'DESC'})
    op.create_index('ix_conversations_last_message_at_desc', 'conversations', [sa.text('last_message_at DESC')], unique=False)
    op.drop_index('ix_lesson_progress_user_lesson', table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_id'), table_name='lesson_progress')
    op.drop_index('ix_lesson_progress_enrollment_lesson', table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_enrollment_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index('ix_enrollments_user_course', table_name='enrollments')
    op.drop_index('ix_enrollments_status_enrolled', table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_enrolled_at'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_lessons_lesson_type'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_index('ix_lessons_course_order', table_name='lessons')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_index('ix_courses_status_created', table_name='courses')
    op.drop_index(op.f('ix_courses_status'), table_name='courses')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_index(op.f('ix_courses_instructor_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index('ix_courses_difficulty_category', table_name='courses')
    op.drop_index(op.f('ix_courses_difficulty'), table_name='courses')
    op.drop_index(op.f('ix_courses_created_at'), table_name='courses')
    op.drop_index(op.f('ix_courses_category'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
