"""Add reviews and ratings tables

Revision ID: c761a30155aa
Revises: 09134aecffed
Create Date: 2025-12-17 04:13:41.019348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c761a30155aa'
down_revision: Union[str, None] = '09134aecffed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('review_type', sa.Enum('opportunity', 'user', 'employer', 'hackathon', name='reviewtypeenum'), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('rating_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Count of reviews for each star rating'),
    sa.Column('ratings_breakdown_avg', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Average scores for additional rating categories'),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_summary_unique', 'review_summaries', ['target_id', 'review_type'], unique=True)
    op.create_index(op.f('ix_review_summaries_average_rating'), 'review_summaries', ['average_rating'], unique=False)
    op.create_index(op.f('ix_review_summaries_target_id'), 'review_summaries', ['target_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_type', sa.Enum('opportunity', 'user', 'employer', 'hackathon', name='reviewtypeenum'), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('ratings_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional ratings like communication, quality, timeliness'),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'flagged', name='reviewstatusenum'), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=False, comment='Whether reviewer actually used the service/opportunity'),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.Column('flag_count', sa.Integer(), nullable=False),
    sa.Column('moderation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_rating', 'reviews', ['rating', 'created_at'], unique=False)
    op.create_index('idx_review_status_created', 'reviews', ['status', 'created_at'], unique=False)
    op.create_index('idx_review_target_type', 'reviews', ['target_id', 'review_type'], unique=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_deleted_at'), 'reviews', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_review_type'), 'reviews', ['review_type'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_target_id'), 'reviews', ['target_id'], unique=False)
    op.create_table('review_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False, comment='spam, inappropriate, offensive, fake, etc.'),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_flags_created_at'), 'review_flags', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_flags_reporter_id'), 'review_flags', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_review_flags_review_id'), 'review_flags', ['review_id'], unique=False)
    op.create_table('review_helpful',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_helpful_unique', 'review_helpful', ['review_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_review_helpful_review_id'), 'review_helpful', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_helpful_user_id'), 'review_helpful', ['user_id'], unique=False)
    op.drop_index('ix_conversations_last_message_at_desc', table_name='conversations')
    op.create_index('ix_conversations_last_message_at_desc', 'conversations', ['last_message_at'], unique=False, postgresql_using='btree', postgresql_ops={'last_message_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_last_message_at_desc', table_name='conversations', postgresql_using='btree', postgresql_ops={'last_message_at': 'DESC'})
    op.create_index('ix_conversations_last_message_at_desc', 'conversations', [sa.text('last_message_at DESC')], unique=False)
    op.drop_index(op.f('ix_review_helpful_user_id'), table_name='review_helpful')
    op.drop_index(op.f('ix_review_helpful_review_id'), table_name='review_helpful')
    op.drop_index('idx_review_helpful_unique', table_name='review_helpful')
    op.drop_table('review_helpful')
    op.drop_index(op.f('ix_review_flags_review_id'), table_name='review_flags')
    op.drop_index(op.f('ix_review_flags_reporter_id'), table_name='review_flags')
    op.drop_index(op.f('ix_review_flags_created_at'), table_name='review_flags')
    op.drop_table('review_flags')
    op.drop_index(op.f('ix_reviews_target_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_review_type'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_deleted_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index('idx_review_target_type', table_name='reviews')
    op.drop_index('idx_review_status_created', table_name='reviews')
    op.drop_index('idx_review_rating', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_review_summaries_target_id'), table_name='review_summaries')
    op.drop_index(op.f('ix_review_summaries_average_rating'), table_name='review_summaries')
    op.drop_index('idx_review_summary_unique', table_name='review_summaries')
    op.drop_table('review_summaries')
    # ### end Alembic commands ###
