"""Create notifications and notification_preferences tables

Revision ID: 49d0c4a0ccde
Revises: f9ff8b11fa2a
Create Date: 2025-12-15 05:00:20.866303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49d0c4a0ccde'
down_revision: Union[str, None] = 'f9ff8b11fa2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enable_match_notifications', sa.Boolean(), nullable=False),
    sa.Column('enable_message_notifications', sa.Boolean(), nullable=False),
    sa.Column('enable_payment_notifications', sa.Boolean(), nullable=False),
    sa.Column('enable_opportunity_notifications', sa.Boolean(), nullable=False),
    sa.Column('enable_system_notifications', sa.Boolean(), nullable=False),
    sa.Column('enable_email_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_match_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_message_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_payment_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_marketing', sa.Boolean(), nullable=False),
    sa.Column('enable_push_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_match_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_message_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_payment_notifications', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False, comment='Enable do-not-disturb hours'),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True, comment='Start time in HH:MM format (24-hour)'),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True, comment='End time in HH:MM format (24-hour)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Notification title/heading'),
    sa.Column('message', sa.Text(), nullable=False, comment='Notification message body'),
    sa.Column('actor_id', sa.UUID(), nullable=True, comment='User who triggered this notification'),
    sa.Column('related_opportunity_id', sa.UUID(), nullable=True),
    sa.Column('related_match_id', sa.UUID(), nullable=True),
    sa.Column('related_message_id', sa.UUID(), nullable=True),
    sa.Column('related_payment_id', sa.UUID(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True, comment='Frontend URL to navigate to when clicked'),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='When notification was read'),
    sa.Column('is_sent_email', sa.Boolean(), nullable=False, comment='Whether email notification was sent'),
    sa.Column('is_sent_push', sa.Boolean(), nullable=False, comment='Whether push notification was sent'),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional notification data'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When notification expires (optional)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_payment_id'], ['payment_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_actor_id'), 'notifications', ['actor_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_priority'), 'notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_notifications_related_match_id'), 'notifications', ['related_match_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_message_id'), 'notifications', ['related_message_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_opportunity_id'), 'notifications', ['related_opportunity_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_payment_id'), 'notifications', ['related_payment_id'], unique=False)
    op.create_index('ix_notifications_type_created', 'notifications', ['notification_type', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_index('ix_conversations_last_message_at_desc', table_name='conversations')
    op.create_index('ix_conversations_last_message_at_desc', 'conversations', ['last_message_at'], unique=False, postgresql_using='btree', postgresql_ops={'last_message_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_last_message_at_desc', table_name='conversations', postgresql_using='btree', postgresql_ops={'last_message_at': 'DESC'})
    op.create_index('ix_conversations_last_message_at_desc', 'conversations', [sa.text('last_message_at DESC')], unique=False)
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index('ix_notifications_type_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_payment_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_opportunity_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_message_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_match_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_priority'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_actor_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
