"""Create analytics tables (user_activities, platform_metrics, system_logs)

Revision ID: 9770b621b903
Revises: a859556b301a
Create Date: 2025-12-15 13:30:56.491317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9770b621b903'
down_revision: Union[str, None] = 'a859556b301a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.DateTime(timezone=True), nullable=False, comment='Date this metric represents'),
    sa.Column('metric_period', sa.String(length=20), nullable=False, comment='Period type: hourly, daily, weekly, monthly'),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False, comment='Users who performed any action'),
    sa.Column('verified_users', sa.Integer(), nullable=False),
    sa.Column('total_opportunities', sa.Integer(), nullable=False),
    sa.Column('new_opportunities', sa.Integer(), nullable=False),
    sa.Column('active_opportunities', sa.Integer(), nullable=False, comment='Published opportunities'),
    sa.Column('opportunity_views', sa.Integer(), nullable=False),
    sa.Column('total_swipes', sa.Integer(), nullable=False),
    sa.Column('total_likes', sa.Integer(), nullable=False),
    sa.Column('total_matches', sa.Integer(), nullable=False),
    sa.Column('new_matches', sa.Integer(), nullable=False),
    sa.Column('match_acceptance_rate', sa.Float(), nullable=True, comment='Percentage of matches that were accepted'),
    sa.Column('total_proposals', sa.Integer(), nullable=False),
    sa.Column('new_proposals', sa.Integer(), nullable=False),
    sa.Column('successful_payments', sa.Integer(), nullable=False),
    sa.Column('failed_payments', sa.Integer(), nullable=False),
    sa.Column('total_payment_volume', sa.Float(), nullable=False, comment='Total payment amount processed'),
    sa.Column('platform_revenue', sa.Float(), nullable=False, comment='Platform fees collected'),
    sa.Column('total_courses', sa.Integer(), nullable=False),
    sa.Column('new_courses', sa.Integer(), nullable=False),
    sa.Column('total_enrollments', sa.Integer(), nullable=False),
    sa.Column('new_enrollments', sa.Integer(), nullable=False),
    sa.Column('course_completions', sa.Integer(), nullable=False),
    sa.Column('average_course_rating', sa.Float(), nullable=True),
    sa.Column('total_conversations', sa.Integer(), nullable=False),
    sa.Column('new_conversations', sa.Integer(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('new_messages', sa.Integer(), nullable=False),
    sa.Column('average_session_duration', sa.Float(), nullable=True, comment='Average session duration in minutes'),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metric data'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_platform_metrics_date_period', 'platform_metrics', ['metric_date', 'metric_period'], unique=True)
    op.create_index(op.f('ix_platform_metrics_id'), 'platform_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_platform_metrics_metric_date'), 'platform_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_platform_metrics_metric_period'), 'platform_metrics', ['metric_period'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False, comment='Log level: debug, info, warning, error, critical'),
    sa.Column('log_category', sa.String(length=50), nullable=False, comment='Category: api, database, payment, auth, etc.'),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True, comment='API endpoint that generated the log'),
    sa.Column('request_id', sa.String(length=255), nullable=True, comment='Request identifier for tracing'),
    sa.Column('exception_type', sa.String(length=255), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_logs_category_created', 'system_logs', ['log_category', 'created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index('ix_system_logs_level_created', 'system_logs', ['log_level', 'created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_log_category'), 'system_logs', ['log_category'], unique=False)
    op.create_index(op.f('ix_system_logs_log_level'), 'system_logs', ['log_level'], unique=False)
    op.create_index(op.f('ix_system_logs_request_id'), 'system_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_system_logs_user_id'), 'system_logs', ['user_id'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who performed the action (null for anonymous)'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Type of event that occurred'),
    sa.Column('event_category', sa.String(length=50), nullable=False, comment='Category: user, opportunity, match, payment, learning, message, general'),
    sa.Column('resource_id', sa.UUID(), nullable=True, comment='ID of related resource (opportunity, course, etc.)'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='Type of resource (opportunity, course, match, etc.)'),
    sa.Column('session_id', sa.String(length=255), nullable=True, comment='Session identifier for grouping events'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address of the user'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='Browser/client user agent'),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional event-specific data'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_activities_category_created', 'user_activities', ['event_category', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_activities_created_at'), 'user_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activities_event_category'), 'user_activities', ['event_category'], unique=False)
    op.create_index('ix_user_activities_event_created', 'user_activities', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_activities_event_type'), 'user_activities', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    op.create_index('ix_user_activities_resource', 'user_activities', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_user_activities_resource_id'), 'user_activities', ['resource_id'], unique=False)
    op.create_index(op.f('ix_user_activities_session_id'), 'user_activities', ['session_id'], unique=False)
    op.create_index('ix_user_activities_user_created', 'user_activities', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    op.drop_index('ix_conversations_last_message_at_desc', table_name='conversations')
    op.create_index('ix_conversations_last_message_at_desc', 'conversations', ['last_message_at'], unique=False, postgresql_using='btree', postgresql_ops={'last_message_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_last_message_at_desc', table_name='conversations', postgresql_using='btree', postgresql_ops={'last_message_at': 'DESC'})
    op.create_index('ix_conversations_last_message_at_desc', 'conversations', [sa.text('last_message_at DESC')], unique=False)
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_index('ix_user_activities_user_created', table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_session_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_resource_id'), table_name='user_activities')
    op.drop_index('ix_user_activities_resource', table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_event_type'), table_name='user_activities')
    op.drop_index('ix_user_activities_event_created', table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_event_category'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_created_at'), table_name='user_activities')
    op.drop_index('ix_user_activities_category_created', table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index(op.f('ix_system_logs_user_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_request_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_log_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_log_category'), table_name='system_logs')
    op.drop_index('ix_system_logs_level_created', table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_index('ix_system_logs_category_created', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_platform_metrics_metric_period'), table_name='platform_metrics')
    op.drop_index(op.f('ix_platform_metrics_metric_date'), table_name='platform_metrics')
    op.drop_index(op.f('ix_platform_metrics_id'), table_name='platform_metrics')
    op.drop_index('ix_platform_metrics_date_period', table_name='platform_metrics')
    op.drop_table('platform_metrics')
    # ### end Alembic commands ###
