"""Create payment proposals and transactions tables

Revision ID: e2cf8603c517
Revises: 04dbd7f8e844
Create Date: 2025-12-14 17:58:56.816313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2cf8603c517'
down_revision: Union[str, None] = '04dbd7f8e844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: All enum types already exist from init-db.sql
    op.create_table('payment_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True, comment='Related opportunity (if applicable)'),
    sa.Column('match_id', sa.UUID(), nullable=True, comment='Related match (if applicable)'),
    sa.Column('proposer_id', sa.UUID(), nullable=False, comment='User who made the proposal'),
    sa.Column('recipient_id', sa.UUID(), nullable=False, comment='User who receives the proposal'),
    sa.Column('payment_type', postgresql.ENUM('hourly', 'fixed', 'milestone', 'commission', name='payment_type_enum', create_type=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Proposed amount'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='For hourly payments'),
    sa.Column('estimated_hours', sa.Integer(), nullable=True, comment='Estimated hours for hourly payments'),
    sa.Column('status', postgresql.ENUM('proposed', 'counter_proposed', 'system_suggested', 'accepted', 'rejected', 'in_progress', 'completed', 'paid', name='payment_status_enum', create_type=False), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='Original proposed amount before counter'),
    sa.Column('counter_count', sa.Integer(), nullable=False, comment='Number of counter proposals'),
    sa.Column('is_ai_suggested', sa.Boolean(), nullable=False, comment='True if suggested by AI'),
    sa.Column('ai_confidence_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='AI confidence score 0-100'),
    sa.Column('description', sa.Text(), nullable=False, comment='Description of work/services'),
    sa.Column('terms', sa.Text(), nullable=True, comment='Payment terms and conditions'),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of milestone objects for milestone payments'),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True, comment='Deadline for work completion'),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Proposal expiration time'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional proposal metadata'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_proposals_created_at'), 'payment_proposals', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_proposals_id'), 'payment_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_payment_proposals_match_id'), 'payment_proposals', ['match_id'], unique=False)
    op.create_index(op.f('ix_payment_proposals_opportunity_id'), 'payment_proposals', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_payment_proposals_proposer_id'), 'payment_proposals', ['proposer_id'], unique=False)
    op.create_index(op.f('ix_payment_proposals_recipient_id'), 'payment_proposals', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_payment_proposals_status'), 'payment_proposals', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('payee_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='Trybe platform fee'),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Amount after platform fee'),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'succeeded', 'failed', 'refunded', 'disputed', name='transaction_status_enum', create_type=False), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True, comment='Stripe PaymentIntent ID'),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=True, comment='Stripe Charge ID'),
    sa.Column('stripe_transfer_id', sa.String(length=255), nullable=True, comment='Stripe Transfer ID to payee'),
    sa.Column('payment_method_type', sa.String(length=50), nullable=True, comment='e.g., card, bank_transfer'),
    sa.Column('last_4_digits', sa.String(length=4), nullable=True, comment='Last 4 digits of card/account'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if transaction failed'),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional transaction metadata'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['payment_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_payee_id'), 'transactions', ['payee_id'], unique=False)
    op.create_index(op.f('ix_transactions_payer_id'), 'transactions', ['payer_id'], unique=False)
    op.create_index(op.f('ix_transactions_proposal_id'), 'transactions', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_stripe_charge_id'), 'transactions', ['stripe_charge_id'], unique=False)
    op.create_index(op.f('ix_transactions_stripe_payment_intent_id'), 'transactions', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_transactions_stripe_transfer_id'), 'transactions', ['stripe_transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_stripe_transfer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_stripe_payment_intent_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_stripe_charge_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_proposal_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payee_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_payment_proposals_status'), table_name='payment_proposals')
    op.drop_index(op.f('ix_payment_proposals_recipient_id'), table_name='payment_proposals')
    op.drop_index(op.f('ix_payment_proposals_proposer_id'), table_name='payment_proposals')
    op.drop_index(op.f('ix_payment_proposals_opportunity_id'), table_name='payment_proposals')
    op.drop_index(op.f('ix_payment_proposals_match_id'), table_name='payment_proposals')
    op.drop_index(op.f('ix_payment_proposals_id'), table_name='payment_proposals')
    op.drop_index(op.f('ix_payment_proposals_created_at'), table_name='payment_proposals')
    op.drop_table('payment_proposals')
    # ### end Alembic commands ###
