"""Create opportunities, swipes, and matches tables

Revision ID: 04dbd7f8e844
Revises: 72902a4304e1
Create Date: 2025-12-14 16:51:02.461907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04dbd7f8e844'
down_revision: Union[str, None] = '72902a4304e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: All enum types already exist from init-db.sql
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('opportunity_type', postgresql.ENUM('full_time', 'part_time', 'contract', 'freelance', 'gig', 'internship', name='opportunity_type_enum', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'closed', 'filled', 'archived', name='opportunity_status_enum', create_type=False), nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Location as JSONB: {country, city, coordinates, remote}'),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('required_skills', postgresql.ARRAY(sa.String()), nullable=True, comment='Array of required skills'),
    sa.Column('preferred_skills', postgresql.ARRAY(sa.String()), nullable=True, comment='Array of preferred skills'),
    sa.Column('experience_level', postgresql.ENUM('entry', 'junior', 'mid', 'senior', 'expert', name='experience_level_enum', create_type=False), nullable=True),
    sa.Column('education_required', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('benefits', postgresql.ARRAY(sa.String()), nullable=True, comment='Array of benefits offered'),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('applications_count', sa.Integer(), nullable=False),
    sa.Column('matches_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_employer_id'), 'opportunities', ['employer_id'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_type'), 'opportunities', ['opportunity_type'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False, comment='Employer who posted the opportunity'),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', 'rejected', 'expired', name='match_status_enum', create_type=False), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True, comment='AI-generated compatibility score 0-100'),
    sa.Column('is_mutual', sa.Boolean(), nullable=False, comment='True if both user and employer liked each other'),
    sa.Column('user_viewed', sa.Boolean(), nullable=False),
    sa.Column('employer_viewed', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional match metadata'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Match expiration time'),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_user_opportunity_match')
    )
    op.create_index(op.f('ix_matches_created_at'), 'matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_matches_employer_id'), 'matches', ['employer_id'], unique=False)
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_opportunity_id'), 'matches', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_user_id'), 'matches', ['user_id'], unique=False)
    op.create_table('swipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('action', postgresql.ENUM('like', 'pass', 'superlike', name='swipe_action_enum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_user_opportunity_swipe')
    )
    op.create_index(op.f('ix_swipes_created_at'), 'swipes', ['created_at'], unique=False)
    op.create_index(op.f('ix_swipes_id'), 'swipes', ['id'], unique=False)
    op.create_index(op.f('ix_swipes_opportunity_id'), 'swipes', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_swipes_user_id'), 'swipes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swipes_user_id'), table_name='swipes')
    op.drop_index(op.f('ix_swipes_opportunity_id'), table_name='swipes')
    op.drop_index(op.f('ix_swipes_id'), table_name='swipes')
    op.drop_index(op.f('ix_swipes_created_at'), table_name='swipes')
    op.drop_table('swipes')
    op.drop_index(op.f('ix_matches_user_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_opportunity_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_employer_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_created_at'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_employer_id'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
