"""Add push notifications tables

Revision ID: ed0ec0bd7027
Revises: c761a30155aa
Create Date: 2025-12-17 04:46:23.791277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0ec0bd7027'
down_revision: Union[str, None] = 'c761a30155aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False, comment='FCM device token'),
    sa.Column('platform', sa.Enum('ios', 'android', 'web', name='deviceplatformenum'), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True, comment="User-friendly device name (e.g., 'iPhone 13', 'Samsung Galaxy')"),
    sa.Column('device_id', sa.String(length=100), nullable=True, comment='Unique device identifier'),
    sa.Column('app_version', sa.String(length=20), nullable=True, comment='App version when token was registered'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this token is still valid'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='Last time a notification was successfully sent to this token'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_token_active', 'device_tokens', ['is_active', 'created_at'], unique=False)
    op.create_index('idx_device_token_user_platform', 'device_tokens', ['user_id', 'platform'], unique=False)
    op.create_index(op.f('ix_device_tokens_created_at'), 'device_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_device_tokens_is_active'), 'device_tokens', ['is_active'], unique=False)
    op.create_index(op.f('ix_device_tokens_platform'), 'device_tokens', ['platform'], unique=False)
    op.create_index(op.f('ix_device_tokens_token'), 'device_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_token_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False, comment='Type: message, opportunity, payment, review, etc.'),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivery_error', sa.String(length=500), nullable=True, comment='Error message if delivery failed'),
    sa.Column('fcm_message_id', sa.String(length=255), nullable=True, comment='Firebase Cloud Messaging message ID'),
    sa.Column('opened', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_token_id'], ['device_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_log_delivered', 'notification_logs', ['delivered', 'sent_at'], unique=False)
    op.create_index('idx_notification_log_type_sent', 'notification_logs', ['notification_type', 'sent_at'], unique=False)
    op.create_index('idx_notification_log_user_sent', 'notification_logs', ['user_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_device_token_id'), 'notification_logs', ['device_token_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_id'), 'notification_logs', ['id'], unique=False)
    op.create_index(op.f('ix_notification_logs_notification_type'), 'notification_logs', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_logs_sent_at'), 'notification_logs', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False)
    op.drop_index('ix_conversations_last_message_at_desc', table_name='conversations')
    op.create_index('ix_conversations_last_message_at_desc', 'conversations', ['last_message_at'], unique=False, postgresql_using='btree', postgresql_ops={'last_message_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_last_message_at_desc', table_name='conversations', postgresql_using='btree', postgresql_ops={'last_message_at': 'DESC'})
    op.create_index('ix_conversations_last_message_at_desc', 'conversations', [sa.text('last_message_at DESC')], unique=False)
    op.drop_index(op.f('ix_notification_logs_user_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_sent_at'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_notification_type'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_device_token_id'), table_name='notification_logs')
    op.drop_index('idx_notification_log_user_sent', table_name='notification_logs')
    op.drop_index('idx_notification_log_type_sent', table_name='notification_logs')
    op.drop_index('idx_notification_log_delivered', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_token'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_platform'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_is_active'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_created_at'), table_name='device_tokens')
    op.drop_index('idx_device_token_user_platform', table_name='device_tokens')
    op.drop_index('idx_device_token_active', table_name='device_tokens')
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
